language: node_js

python:
  - "3.8"

services:
  - docker

before_install:
  # install yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

  # install python 3.8
  - sudo apt update
  - sudo apt install -y software-properties-common
  - sudo add-apt-repository -y ppa:deadsnakes/ppa
  - sudo apt update
  - sudo apt install -y python3.8 python3-pip python3-dev build-essential pthon3-setuptools python3-wheel
  - sudo update-alternatives --install /usr/bin/python python /usr/bin/python3.8 10
  - sudo update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 10
  - sudo pip install --upgrade pip setuptools
  - sudo pip install --upgrade pipenv

  # install pipenv
  - export AWS_ACCESS_KEY_ID=KEY_ID
  - export AWS_SECRET_ACCESS_KEY=KEY
